[config]

# █▀▄ █▄█ █▄░█ ▄▀█ █▀▄▀█ █ █▀▀
# █▄▀ ░█░ █░▀█ █▀█ █░▀░█ █ █▄▄
# ============================
# See changes immediately.

[templates.hyprland]
input_path  = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook   = 'hyprctl reload config-only'

[templates.waybar]
input_path  = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook   = 'pkill -SIGUSR2 waybar'

[templates.cava]
input_path  = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/colors'
post_hook   = "pkill -USR1 cava"

# NOTE: Everything is colorcoded here... ls_colors etc. So, no generation.
# UPDATE: colorcoding issue solved with custom_colors. But looks a bit off for my taste.
# [templates.kitty]
# input_path  = '~/.config/matugen/templates/kitty.conf'
# output_path = '~/.config/kitty/colors/colors.conf'
# post_hook   = 'pkill -SIGUSR1 kitty'

# █▀ ▀█▀ ▄▀█ ▀█▀ █ █▀▀
# ▄█ ░█░ █▀█ ░█░ █ █▄▄
# ====================
# Changes visible only after app restart.

[templates.btop]
input_path  = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/colors.theme'

[templates.fuzzel]
input_path  = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

# [config.custom_colors]
# red     = { color = "#f38ba8", blend = true }
# green   = { color = "#a6e3a1", blend = true }
# yellow  = { color = "#f9e2af", blend = true }
# blue    = { color = "#89b4fa", blend = true }
# magenta = { color = "#f5c2e7", blend = true }
# cyan    = { color = "#94e2d5", blend = true }
# white   = { color = "#e6e6e6", blend = true }
